<?php
/**
 * @var $block MageGuide\FirstModule\Block\BlogPost
 */
    $blogPost = $block->getBlogPost();
?>

<article class="blogpost">
    <h2><?=$block->escapeHtml($blogPost->getTitle());?></h2>
    <section>
        <?=$block->escapeHtml($blogPost->getPost());?>
    </section>
</article>

<?php

 $products = $block->getRelatedProducts($blogPost->getSkus());
?>

<section style="display: flex; flex-direction: row;">
    <?php foreach ($products as $product): ?>
        <div>
            <?=$block->getImageHtml($product);?>
            <h4>
                <?=$product->getName(); ?>
            </h4>
        </div>
    <?php endforeach; ?>
</section>
