<?php
    /**
     * @var $block MageGuide\FirstModule\Block\BlogPostList
     */
    $blogposts = $block->getBlogPosts();

    if (count($blogposts) <= 0){
        echo "<div>NO blog Posts</div>";
        return;
    }

?>

<?=$block->getPaginatedBlogPosts()->toHtml();?>

<?php
    /**
     * @var $blogpost \MageGuide\FirstModule\Model\BlogPost
     */
    foreach ($blogposts as $blogpost): ?>
        <article class="blogpostpreview">
            <h2><?=$block->escapeHtml($blogpost->getTitle());?></h2>
            <section>
                <?=$block->escapeHtml(substr($blogpost->getPost(),0,10));?> ... <a href="<?=$block->getUrl("blog/blogpost",['blogpost_id'=>1]);?>">Read More</a>
            </section>
        </article>
<?php endforeach; ?>

