<?php
    /**
     * @var $block MageGuide\FirstModule\Block\HelloWord
     */
    $blogposts = $block->getAllBlogPosts();

    if (count($blogposts) > 0){
        echo "<div>NO blog Posts</div>";
        return;
    }
?>

<?php foreach ($blogposts as $blogpost): ?>
        <article>
            <h2><?=$block->escapeHtml($blogpost->getTitle());?></h2>
            <section>
                <?=$block->escapeHtml($blogpost->getPost());?>
            </section>
        </article>
<?php endforeach; ?>
