<?php

namespace MageGuide\FirstModule\Model\BlogPost;

use MageGuide\FirstModule\Model\Factories\BlogPost\CollectionFactory;
use Magento\Ui\DataProvider\AbstractDataProvider;

class DataProvider extends AbstractDataProvider
{

    private CollectionFactory $blogpostFactory;

    public function __construct(
        $name,
        $primaryFieldName,
        $requestFieldName,
        CollectionFactory $blogpostFactory,
        array $meta = [],
        array $data = []
    ){
        $this->blogpostFactory = $blogpostFactory;
        parent::__construct($name, $primaryFieldName, $requestFieldName, $meta, $data);
    }

    public function getRequestFieldName()
    {
        return parent::getRequestFieldName(); // TODO: Change the autogenerated stub
    }

    public function getCollection()
    {
        return $this->blogpostFactory->create();
    }
}
